hostname R1
service integrated-vtysh-config

!
! Interfaces
!

interface eth0
 ip address 1.0.0.1/30

interface eth1
 ip address 1.0.0.5/30

interface eth2
 ip address 1.0.0.9/30

interface lo
 ip address 10.0.0.1/32

!
! OSPF Underlay
!

router ospf
 network 1.0.0.0/30 area 0
 network 1.0.0.4/30 area 0
 network 1.0.0.8/30 area 0
 network 10.0.0.1/32 area 0

!
! iBGP + Route Reflector
!

router bgp 65000
 bgp router-id 10.0.0.1

 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.3 remote-as 65000
 neighbor 10.0.0.4 remote-as 65000

 neighbor 10.0.0.2 update-source lo
 neighbor 10.0.0.3 update-source lo
 neighbor 10.0.0.4 update-source lo

 !
 ! Route Reflector Clients
 !
 neighbor 10.0.0.2 route-reflector-client
 neighbor 10.0.0.3 route-reflector-client
 neighbor 10.0.0.4 route-reflector-client

 !
 ! Advertise Loopback
 !
 address-family ipv4 unicast
  network 10.0.0.1/32
 exit-address-family

 !
 ! EVPN address family — activate EVPN with each leaf and reflect their routes
 !
 address-family l2vpn evpn
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.3 activate
  neighbor 10.0.0.4 activate
  neighbor 10.0.0.2 route-reflector-client
  neighbor 10.0.0.3 route-reflector-client
  neighbor 10.0.0.4 route-reflector-client
 exit-address-family