hostname R3
service integrated-vtysh-config

!
! Interfaces
!

interface eth0
 ip address 1.0.0.17/30

interface eth1
 ip address 1.0.0.6/30

interface lo
 ip address 10.0.0.3/32

!
! OSPF Underlay
!

router ospf
 network 1.0.0.4/30 area 0
 network 1.0.0.16/30 area 0
 network 10.0.0.3/32 area 0

!
! iBGP
!

router bgp 65000
 bgp router-id 10.0.0.3

 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 update-source lo

 address-family ipv4 unicast
  network 10.0.0.3/32
 exit-address-family